"""fix tables

Revision ID: b488824a53e6
Revises: 3503ab45ccd6
Create Date: 2025-04-07 11:39:00.709367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b488824a53e6'
down_revision: Union[str, None] = '3503ab45ccd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('cooking_minute', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foods', 'cooking_minute')
    # ### end Alembic commands ###
